apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bad-pod
  name: bad-pod
spec:
  containers:
  - image: nginx
    name: bad-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
